version: '3.8'

services:
  game-server:
    build: ./server
    restart: always
    ports:

      - "4433-4483:4433/udp"
    extra_hosts:
      "my-database:192.168.5.87"
      "my-login-server:192.168.5.87"
    deploy:
      mode: replicated
      replicas: 50