version: '3.8'

services:
  login-server:
    build: ./loginserver
    restart: always
    ports:
      - "8820:8820"
    environment:
      - LB_IP=192.168.1.156
    volumes:
      - ./loginserver/game.db:/loginserver/game.db
    extra_hosts:
      - "load-balancer-server:192.168.1.156"

volumes:
  login_db_data: