version: '3.8'

services:
  game-server:
    build: ./loadBalancer
    restart: always
    ports:
      - "8080:8080/udp"
    extra_hosts:
      "my-game-server:192.168.5.87"
      "my-login-server:192.168.5.87"