version: '3.8'

services:
  load-balancer-server:
    build: ./loadBalancer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LOGIN_IP=192.168.5.87
    extra_hosts:
      - "game-server:192.168.5.87"
      - "login-server:192.168.5.87"